/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.gui;

import com.project.controller.Controller;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jabref.BibtexEntry;

/**
 *
 * @author mariane
 */
public class FileChoose extends javax.swing.JFrame {

    public File f1 = null;
    public File f2 = null;

    /**
     * Creates new form FileChoose
     */
    public FileChoose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        File1Label = new javax.swing.JLabel();
        File2Label = new javax.swing.JLabel();
        File1Textfield = new javax.swing.JTextField();
        File2TextField = new javax.swing.JTextField();
        File1Button = new javax.swing.JButton();
        File2Button = new javax.swing.JButton();
        VerifyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IntersecoesTextArea = new javax.swing.JTextArea();
        TotalTextfield = new javax.swing.JTextField();
        TotalLabel = new javax.swing.JLabel();

        jFileChooser1.setDialogTitle("Arquivos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interseção Entre Bases");
        setPreferredSize(new java.awt.Dimension(865, 551));

        File1Label.setText("File1");

        File2Label.setText("File2");

        File1Button.setText("Search");
        File1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                File1ButtonMouseClicked(evt);
            }
        });

        File2Button.setText("Search");
        File2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                File2ButtonMouseClicked(evt);
            }
        });

        VerifyButton.setText("Verificar");
        VerifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerifyButtonMouseClicked(evt);
            }
        });

        IntersecoesTextArea.setColumns(20);
        IntersecoesTextArea.setRows(5);
        jScrollPane1.setViewportView(IntersecoesTextArea);

        TotalTextfield.setEditable(false);
        TotalTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTextfieldActionPerformed(evt);
            }
        });

        TotalLabel.setText("Total de arquivos Iguais entre as duas bases: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(File1Label)
                                .addGap(18, 18, 18)
                                .addComponent(File1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(File2Label)
                                .addGap(18, 18, 18)
                                .addComponent(File2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(File1Button)
                            .addComponent(File2Button))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VerifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(File1Label)
                    .addComponent(File1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(File1Button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(File2Label)
                    .addComponent(File2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(File2Button))
                .addGap(18, 18, 18)
                .addComponent(VerifyButton)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel)
                    .addComponent(TotalTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void File1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_File1ButtonMouseClicked
        this.f1 = openFileChooser(this.File1Textfield);
    }//GEN-LAST:event_File1ButtonMouseClicked

    private void File2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_File2ButtonMouseClicked
        this.f2 = openFileChooser(this.File2TextField);
    }//GEN-LAST:event_File2ButtonMouseClicked

    private void VerifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyButtonMouseClicked
        Controller controller = new Controller(this.f1, this.f2);
        controller.getIntersectionBib();

        String context = "";
        int i = 0;
        if (controller.intersecao.isEmpty()) {
            showMessage("Não há interseção entre as bases", controller.intersecao.size());
        } else {
            for (BibtexEntry entry : controller.intersecao) {
                context = context.concat(String.valueOf(i)).concat(". ").concat(entry.getField("title").concat("\n"));
                i++;
            }
            showMessage(context, controller.intersecao.size());
        }

    }//GEN-LAST:event_VerifyButtonMouseClicked

    private void TotalTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChoose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton File1Button;
    private javax.swing.JLabel File1Label;
    private javax.swing.JTextField File1Textfield;
    private javax.swing.JButton File2Button;
    private javax.swing.JLabel File2Label;
    private javax.swing.JTextField File2TextField;
    private javax.swing.JTextArea IntersecoesTextArea;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JTextField TotalTextfield;
    private javax.swing.JButton VerifyButton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private File openFileChooser(JTextField textfield) {
        int returnVal = jFileChooser1.showOpenDialog(this);
        File file = null;
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser1.getSelectedFile();
            if (!file.getName().endsWith(".bib")) {
                JOptionPane.showMessageDialog(rootPane, "A extensão do arquivo não é .bib", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    // What to do with the file, e.g. display it in a TextArea
                    textfield.read(new FileReader(file.getAbsolutePath()), null);
                    textfield.setText(file.getName());
                } catch (IOException ex) {
                    System.out.println("problem accessing file" + file.getAbsolutePath());
                }
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
        return file;
    }

    public void showMessage(String mensagem, int size) {
        this.IntersecoesTextArea.append(mensagem);
        this.TotalTextfield.setText(String.valueOf(size));
    }

}
